package proyecto.pojos;
// Generated 10-feb-2016 10:12:00 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dept generated by hbm2java
 */
@Entity
@Table(name = "dept", catalog = "scott")
public class Departamento implements java.io.Serializable {

	@Id
	@Column(name = "deptno", unique = true, nullable = false, precision = 2, scale = 0)
	private byte deptno;
	
	@Column(name = "dname", length = 14)
	private String dname;
	
	@Column(name = "loc", length = 13)
	private String loc;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "dept")
	private Set<Empleado> emps = new HashSet<Empleado>(0);

	public Departamento() {
	}

	public Departamento(byte deptno) {
		this.deptno = deptno;
	}

	public Departamento(byte deptno, String dname, String loc, Set<Empleado> emps) {
		this.deptno = deptno;
		this.dname = dname;
		this.loc = loc;
		this.emps = emps;
	}

	
	public byte getDeptno() {
		return this.deptno;
	}

	public void setDeptno(byte deptno) {
		this.deptno = deptno;
	}

	
	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	
	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	
	public Set<Empleado> getEmps() {
		return this.emps;
	}

	public void setEmps(Set<Empleado> emps) {
		this.emps = emps;
	}

}
