package proyecto.pojos;
// Generated 10-feb-2016 10:12:00 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name = "emp", catalog = "scott")
public class Empleado implements java.io.Serializable {
	
	@Id

	@Column(name = "empno", unique = true, nullable = false, precision = 4, scale = 0)
	private short empno;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "deptno")
	private Departamento dept;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mgr")
	private Empleado empleadoJefe;
	
	@Column(name = "ename", length = 10)
	private String ename;
	
	@Column(name = "job", length = 9)
	private String job;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "hiredate", length = 10)
	private Date hiredate;
	
	@Column(name = "sal", precision = 7 , scale = 2)
	private BigDecimal sal;
	
	@Column(name = "comm", precision = 7 , scale = 2)
	private BigDecimal comm;
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "empleadoJefe")
	private Set<Empleado> subordinados = new HashSet<Empleado>(0);

	public Empleado() {
	}

	public Empleado(short empno) {
		this.empno = empno;
	}

	public Empleado(short empno, Departamento dept, Empleado empleadoJefe, String ename, String job, Date hiredate, BigDecimal sal,
			BigDecimal comm, Set<Empleado> subordinados) {
		this.empno = empno;
		this.dept = dept;
		this.empleadoJefe = empleadoJefe;
		this.ename = ename;
		this.job = job;
		this.hiredate = hiredate;
		this.sal = sal;
		this.comm = comm;
		this.subordinados = subordinados;
	}

	
	public short getEmpno() {
		return this.empno;
	}

	public void setEmpno(short empno) {
		this.empno = empno;
	}

	
	public Departamento getDept() {
		return this.dept;
	}

	public void setDept(Departamento dept) {
		this.dept = dept;
	}


	public Empleado getEmpleadoJefe() {
		return this.empleadoJefe;
	}

	public void setEmpleadoJefe(Empleado empleadoJefe) {
		this.empleadoJefe = empleadoJefe;
	}

	
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}


	public Date getHiredate() {
		return this.hiredate;
	}

	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}


	public BigDecimal getSal() {
		return this.sal;
	}

	public void setSal(BigDecimal sal) {
		this.sal = sal;
	}


	public BigDecimal getComm() {
		return this.comm;
	}

	public void setComm(BigDecimal comm) {
		this.comm = comm;
	}


	public Set<Empleado> getSubordinados() {
		return this.subordinados;
	}

	public void setSubordinados(Set<Empleado> subordinados) {
		this.subordinados = subordinados;
	}

}
